virtualMachines:
  - name: win11-vm1
    namespace: default
    storage: 60Gi
    hostPath: /var/vm/images/win11-1
    storageClassName: openebs-lvmpv
    cpuCores: 3
    memory: 12288Mi
    gpuDeviceName: intel.com/sriov-gpudevice
    secureBoot: false
    usePVC: false
    useDataVolume: true
    dataVolumeName: vm1-win11-image
    cdromImage: docker.io/intel2019/win11-iso-cdisk
    bootDiskImage: docker.io/aisha123aisha/disk-win-11
    virtioContainerDiskImage: docker.io/kubevirt/virtio-container-disk
    driverDiskImage: docker.io/intel2019/win-softwaredrv-iso-cdisk
    rdpPort: 3390
    deviceplugin:
      resources:
        igpu: 1
        x11: 1
        udma: 1
        vfio: 1
        usb: 1
    sidecar: 
      scriptName: 'metadata-xml.sh'
      display:
        gtkgl: 'on'
        fullScreen: 'on'
        zoomToFit: 'on'
        windowClose: 'off'
        input: 'off'
        connectors: 'HDMI-1'
      env:
        display: ':0'
      usb:
        host: 'usb-host'
        hostbus_dev1: '3'
        hostport_dev1: '3.1'
        hostbus_dev2: '3'
        hostport_dev2: '3.2'

#  - name: win11-vm2
#    namespace: default
#    storage: 60Gi
#    hostPath: /var/vm/images/win11-2
#    storageClassName: openebs-lvmpv
#    cpuCores: 3
#    memory: 12288Mi
#    gpuDeviceName: intel.com/sriov-gpudevice
#    secureBoot: false
#    usePVC: false
#    useDataVolume: false
#    dataVolumeName: vm2-win11-image
#    cdromImage: docker.io/intel2019/win11-iso-cdisk
#    bootDiskImage: docker.io/aisha123aisha/disk-win-11
#    virtioContainerDiskImage: docker.io/kubevirt/virtio-container-disk
#    driverDiskImage: docker.io/intel2019/win-softwaredrv-iso-cdisk
#    rdpPort: 3390
#    deviceplugin:
#      resources:
#        igpu: 1
#        x11: 1
#        udma: 1
#        vfio: 1
#        usb: 1
#    sidecar: 
#      scriptName: 'metadata-xml.sh'
#      display:
#         gtkgl: 'on'
#         fullScreen: 'on'
#         zoomToFit: 'on'
#         windowClose: 'off'
#         input: 'off'
#         connectors: 'HDMI-2'
#      env:
#         display: ':0'
#      usb:
#         host: 'usb-host'
#         hostbus_dev1: '3'
#         hostport_dev1: '3.3'
#        hostbus_dev2: '3'
#        hostport_dev2: '3.4'

#   - name: win11-vm3
#     namespace: default
#     storage: 60Gi
#     hostPath: /var/vm/images/win11-3
#     storageClassName: openebs-lvmpv
#     cpuCores: 3
#     memory: 12288Mi
#     gpuDeviceName: intel.com/sriov-gpudevice
#     secureBoot: false
#     usePVC: false
#     cdromImage: docker.io/intel2019/win11-iso-cdisk
#     bootDiskImage: docker.io/aisha123aisha/disk-win-11
#     virtioContainerDiskImage: docker.io/kubevirt/virtio-container-disk
#     driverDiskImage: docker.io/intel2019/win-softwaredrv-iso-cdisk
#     rdpPort: 3390
#     deviceplugin:
#       resources:
#         igpu: 1
#         x11: 1
#         udma: 1
#         vfio: 1
#         usb: 1
#     sidecar: 
#       scriptName: 'metadata-xml.sh'
#       display:
#         gtkgl: 'on'
#         fullScreen: 'on'
#         zoomToFit: 'on'
#         windowClose: 'off'
#         input: 'off'
#         connectors: 'DP-1'
#       env:
#         display: ':0'
#       usb:
#         host: 'usb-host'
#         hostbus_dev1: '3'
#         hostport_dev1: '2.1'
#         hostbus_dev2: '3'
#         hostport_dev2: '2.2'

#   - name: win11-vm4
#     namespace: default
#     storage: 60Gi
#     hostPath: /var/vm/images/win11-4
#     storageClassName: openebs-lvmpv
#     cpuCores: 3
#     memory: 12288Mi
#     gpuDeviceName: intel.com/sriov-gpudevice
#     secureBoot: false
#     usePVC: false
#     cdromImage: docker.io/intel2019/win11-iso-cdisk
#     bootDiskImage: docker.io/aisha123aisha/disk-win-11
#     virtioContainerDiskImage: docker.io/kubevirt/virtio-container-disk
#     driverDiskImage: docker.io/intel2019/win-softwaredrv-iso-cdisk
#     rdpPort: 3390
#     deviceplugin:
#       resources:
#         igpu: 1
#         x11: 1
#         udma: 1
#         vfio: 1
#         usb: 1
#     sidecar: 
#       scriptName: 'metadata-xml.sh'
#       display:
#         gtkgl: 'on'
#         fullScreen: 'on'
#         zoomToFit: 'on'
#         windowClose: 'off'
#         input: 'off'
#         connectors: 'DP-3'
#       env:
#         display: ':0'
#       usb:
#         host: 'usb-host'
#         hostbus_dev1: '3'
#         hostport_dev1: '2.3'
#         hostbus_dev2: '3'
#         hostport_dev2: '2.4'
