apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec:
  containers:
  - name: test-container
    image: ubuntu
    command: ["sleep", "infinity"]
    resources:
      limits:
        intel.com/x11: 100
        intel.com/udma: 100
        intel.com/igpu: 100
        intel.com/usb: 100
        intel.com/vfio: 100